name: Check monthly DLUO and send it to Notion
on:
  # Tous les 1ers du mois à 00:00 UTC
  schedule:
    - cron: '0 0 1 * *'
  # déclenchement manuel si besoin
  workflow_dispatch:

jobs:
  check-dluo:
    runs-on: ubuntu-22.04
    outputs:
      generate-dluo-table-result: ${{ steps.generate-dluo-table.outputs.result }}
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
      - name: Install pnpm
        uses: pnpm/action-setup@bdf0af2a9d539c0fd91f655344d2934bfd5a2cdd
        with:
          version: 10.11.0
      - name: Use Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e
        with:
          node-version-file: './package.json'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile
      - run: git log | head && git status
      - id: compilation
        name: Compile FR
        run: pnpm compile:fr
      - id: generate-dluo-table
        name: Generate DLUO table
        run: |
          output=$(node scripts/DLUO/check_DLUO.mjs)
          encoded=$(echo "$output" | base64 | tr -d '\n')
          echo "result=$encoded" >> $GITHUB_OUTPUT

  create-notion-card:
    runs-on: ubuntu-22.04
    needs: check-dluo
    steps:
      - name: Create Notion card
        run: |
          echo "${{ needs.check-dluo.outputs.generate-dluo-table-result }}" | base64 -d > payload_temp.json
          sed "s/NOTION_DATABASE_PLACEHOLDER/${{ secrets.NOTION_DATABASE }}/g" payload_temp.json > payload.json
          curl -X POST "https://api.notion.com/v1/pages" \
          -H "Authorization: Bearer ${{ secrets.NOTION_API_KEY }}" \
          -H "Content-Type: application/json" \
          -H "Notion-Version: 2022-06-28" \
          --data @payload.json
